In [2]:
import numpy as np

In [3]:
arr_1 = np.full((3, 4), 3)
print (arr_1)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [4]:
arr_2 = np.random.randint(0, 10, size=(2, 4))
print (arr_2)

[[9 3 0 9]
 [1 6 3 1]]


In [5]:
newArr = np.concatenate((arr_2, arr_1), axis=0)
print (newArr)

[[9 3 0 9]
 [1 6 3 1]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [6]:
tuple = (1, 8, 6, 5, 8, 3)
arr_3 = np.array(tuple)
print(arr_3)

[1 8 6 5 8 3]


In [7]:
arr_4  = arr_3 * 3 + 1
print (arr_4)

[ 4 25 19 16 25 10]


In [8]:
arr_5 = arr_3.reshape((2,3))
print(arr_5)

[[1 8 6]
 [5 8 3]]


In [9]:
print (np.min(arr_5, axis=1))

[1 3]


In [10]:
print (np.mean(arr_5))

5.166666666666667


In [11]:
arr_6 = np.arange(11) ** 2
print (arr_6)

[  0   1   4   9  16  25  36  49  64  81 100]


In [12]:
print(arr_6[::2])

[  0   4  16  36  64 100]


In [13]:
print(arr_6[::-1])

[100  81  64  49  36  25  16   9   4   1   0]


In [14]:
arr_6[1::2] = 2
print(arr_6)

[  0   2   4   2  16   2  36   2  64   2 100]


In [15]:
if np.any((ch := 49) == arr_6):
    print(f"{ch} есть в массиве.")
else:
    print(f"{ch} нет в массиве.")

49 нет в массиве.


In [19]:
def GetNegative(array):
  return array[array < 0]

arr_A = np.array([[2, -3, -9],
                  [0, -5, 7], 
                  [1, 6, -2], 
                  [-5, -10, 3]])
arr_B = GetNegative(arr_A)
    
print(arr_A)
print(arr_B)

[[  2  -3  -9]
 [  0  -5   7]
 [  1   6  -2]
 [ -5 -10   3]]
[ -3  -9  -5  -2  -5 -10]
